



<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<!-- ViewVC :: http://www.viewvc.org/ -->
<head>
<title>[php-apt-parser] Log of /trunk/parse-apt-files.inc</title>
<meta name="generator" content="ViewVC 1.1.5" />
<link rel="shortcut icon" href="/viewvc/*docroot*/images/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="/viewvc/*docroot*/styles.css" type="text/css" />

</head>
<body>
<div class="vc_navheader">
<table><tr>
<td><strong><a href="/viewvc"><span class="pathdiv">/</span></a><a href="/viewvc/php-apt-parser/">[php-apt-parser]</a><span class="pathdiv">/</span><a href="/viewvc/php-apt-parser/trunk/">trunk</a><span class="pathdiv">/</span>parse-apt-files.inc</strong></td>
<td style="text-align: right;"></td>
</tr></table>
</div>
<div style="float: right; padding: 5px;"><a href="http://www.viewvc.org/" title="ViewVC Home"><img src="/viewvc/*docroot*/images/viewvc-logo.png" alt="ViewVC logotype" width="240" height="70" /></a></div>
<h1>Log of /trunk/parse-apt-files.inc</h1>

<p style="margin:0;">

<a href="/viewvc/php-apt-parser/trunk/"><img src="/viewvc/*docroot*/images/back_small.png" class="vc_icon" alt="Parent Directory" /> Parent Directory</a>

| <a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?view=log"><img src="/viewvc/*docroot*/images/log.png" class="vc_icon" alt="Revision Log" /> Revision Log</a>




</p>

<hr />
<table class="auto">



<tr>
<td>Links to HEAD:</td>
<td>
(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?view=markup">view</a>)
(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?view=co">download</a>)

(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?view=annotate">annotate</a>)
</td>
</tr>



<tr>
<td>Sticky Revision:</td>
<td><form method="get" action="/viewvc/php-apt-parser" style="display: inline">
<div style="display: inline">
<input type="hidden" name="orig_pathtype" value="FILE"/><input type="hidden" name="orig_view" value="log"/><input type="hidden" name="orig_path" value="trunk/parse-apt-files.inc"/><input type="hidden" name="view" value="redirect_pathrev"/>

<input type="text" name="pathrev" value="" size="6"/>

<input type="submit" value="Set" />
</div>
</form>

</td>
</tr>
</table>
 







<div>
<hr />

<a name="rev36"></a>


Revision <a href="/viewvc/php-apt-parser?view=revision&amp;revision=36"><strong>36</strong></a> -


(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?revision=36&amp;view=markup">view</a>)


(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?revision=36&amp;view=co">download</a>)

(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?annotate=36">annotate</a>)



- <a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?r1=36&amp;view=log">[select for diffs]</a>




<br />

Modified

<em>Fri Dec 12 23:53:39 2008 UTC</em>
(3 years, 3 months ago)
by <em>dleidert-guest</em>









<br />File length: 11368 byte(s)







<br />Diff to <a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?r1=33&amp;r2=36">previous 33</a>







<pre class="vc_log">2008-12-12  Daniel Leidert  &lt;<a href="mailto:daniel.leidert%40wgdd.de">&#100;&#97;&#110;&#105;&#101;&#108;&#46;&#108;&#101;&#105;&#100;&#101;&#114;&#116;&#64;&#119;&#103;&#100;&#100;&#46;&#100;&#101;</a>&gt;, 1.3.7:
	* parse-apt-files.inc (parse_and_list):
	  - WCAG related improvement. Add the cite attribute to blockquote and
	    point to the pool location.

</pre>
</div>



<div>
<hr />

<a name="rev33"></a>


Revision <a href="/viewvc/php-apt-parser?view=revision&amp;revision=33"><strong>33</strong></a> -


(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?revision=33&amp;view=markup">view</a>)


(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?revision=33&amp;view=co">download</a>)

(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?annotate=33">annotate</a>)



- <a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?r1=33&amp;view=log">[select for diffs]</a>




<br />

Modified

<em>Tue Jan  8 13:19:51 2008 UTC</em>
(4 years, 3 months ago)
by <em>dleidert-guest</em>









<br />File length: 11240 byte(s)







<br />Diff to <a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?r1=32&amp;r2=33">previous 32</a>







<pre class="vc_log">* LICENSE, parse-apt-files.inc:
  - Fixed copyright (welcome 2008).

</pre>
</div>



<div>
<hr />

<a name="rev32"></a>


Revision <a href="/viewvc/php-apt-parser?view=revision&amp;revision=32"><strong>32</strong></a> -


(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?revision=32&amp;view=markup">view</a>)


(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?revision=32&amp;view=co">download</a>)

(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?annotate=32">annotate</a>)



- <a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?r1=32&amp;view=log">[select for diffs]</a>




<br />

Modified

<em>Tue Jan  8 13:17:58 2008 UTC</em>
(4 years, 3 months ago)
by <em>dleidert-guest</em>









<br />File length: 11240 byte(s)







<br />Diff to <a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?r1=13&amp;r2=32">previous 13</a>







<pre class="vc_log">* Merged des branch into trunk. I think, this is stable enough.

* Fixed ChangeLog timestamps.

</pre>
</div>



<div>
<hr />

<a name="rev13"></a>


Revision <a href="/viewvc/php-apt-parser?view=revision&amp;revision=13"><strong>13</strong></a> -


(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?revision=13&amp;view=markup">view</a>)


(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?revision=13&amp;view=co">download</a>)

(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?annotate=13">annotate</a>)



- <a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?r1=13&amp;view=log">[select for diffs]</a>




<br />

Modified

<em>Sat Jun 24 23:58:51 2006 UTC</em>
(5 years, 9 months ago)
by <em>des-guest</em>









<br />File length: 6708 byte(s)







<br />Diff to <a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?r1=3&amp;r2=13">previous 3</a>







<pre class="vc_log">Added ChangeLog file and removed the (now) redundant info from parse-apt-files.inc itself.
</pre>
</div>



<div>
<hr />

<a name="rev3"></a>


Revision <a href="/viewvc/php-apt-parser?view=revision&amp;revision=3"><strong>3</strong></a> -


(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?revision=3&amp;view=markup">view</a>)


(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?revision=3&amp;view=co">download</a>)

(<a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?annotate=3">annotate</a>)



- <a href="/viewvc/php-apt-parser/trunk/parse-apt-files.inc?r1=3&amp;view=log">[select for diffs]</a>




<br />

Added

<em>Sun May 14 00:31:02 2006 UTC</em>
(5 years, 11 months ago)
by <em>dleidert-guest</em>







<br />File length: 7773 byte(s)











<pre class="vc_log">Initially added Jarno's version 1.2 of the script.</pre>
</div>

 


 <hr />
<p><a name="diff"></a>
This form allows you to request diffs between any two revisions of this file.
For each of the two "sides" of the diff,

enter a numeric revision.

</p>
<form method="get" action="/viewvc/php-apt-parser/trunk/parse-apt-files.inc" id="diff_select">
<table cellpadding="2" cellspacing="0" class="auto">
<tr>
<td>&nbsp;</td>
<td>
<input type="hidden" name="view" value="diff"/>
Diffs between

<input type="text" size="12" name="r1"
value="36" />

and

<input type="text" size="12" name="r2" value="3" />

</td>
</tr>
<tr>
<td>&nbsp;</td>
<td>
Type of Diff should be a
<select name="diff_format" onchange="submit()">
<option value="h" selected="selected">Colored Diff</option>
<option value="l" >Long Colored Diff</option>
<option value="f" >Full Colored Diff</option>
<option value="u" >Unidiff</option>
<option value="c" >Context Diff</option>
<option value="s" >Side by Side</option>
</select>
<input type="submit" value=" Get Diffs " />
</td>
</tr>
</table>
</form>





<hr />
<table>
<tr>
<td>&nbsp;</td>
<td style="text-align: right;"><strong><a href="/viewvc/*docroot*/help_log.html">ViewVC Help</a></strong></td>
</tr>
<tr>
<td>Powered by <a href="http://viewvc.tigris.org/">ViewVC 1.1.5</a></td>
<td style="text-align: right;">&nbsp;</td>
</tr>
</table>
</body>
</html>


